### PR TITLE
fix '.wheel' to 'WheelPickerStyle()' in MainFeedView.swift

### PR DESCRIPTION
**Pull request by akiniru**
Hello,
I found and fixed the code that was failing due to an iOS build failure.

### CODE REVIEW

**Comment by terrakok** [comment]
🤔 could you describe the failure? i can't reproduce the error

**Comment by akiniru** [comment]
스크린샷 2022-02-04 오전 11 14 38
This is the error message. 'Cannot infer contextual base in reference to member 'wheel''

**Comment by JUSTINMKAUFMAN** [comment]
> 스크린샷 2022-02-04 오전 11 14 38 This is the error message. 'Cannot infer contextual base in reference to member 'wheel''

Using the enum style `.wheel` is valid with the iOS min deployment target of 14.0 (which this project uses by default, I think?). I'm guessing you tried lowering the target to 13.0, which then requires you to use the older style syntax.

**Comment by akiniru** [comment]
Oh. I'm sorry 😢

**Pull request closed without merging**
